# Generated by Django 3.0.7 on 2021-03-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('per_price', models.IntegerField(default=1)),
                ('total_price', models.IntegerField(default=1)),
            ],
        ),
    ]
