# Generated by Django 3.0.5 on 2020-06-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200620_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/profile.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
